### ISSUE TITLE
Inconsistent case sensitivity in function names

### ISSUE THREAD

**Issue by mudrd8mz** [PlaneteStream/moodle-atto_planetestream#2]
The function is declared as `funcobfuscate()` yet it is called as `funcObfuscate()`. Even though PHP functions as case-insensitive, it is more than warmly welcome to keep the consistency.

In any case, this function is subject of bug #1 too.

**Comment by mudrd8mz** [comment]
This applies to your TinyMCE plugin, too.

**Comment by PlaneteStream** [comment]
Addressed.
