### ISSUE TITLE
Error in plugin - missing $PAGE-> in front of pagetype

### ISSUE THREAD

**Issue by mcardle** [PlaneteStream/moodle-atto_planetestream#7]
https://github.com/PlaneteStream/moodle-atto_planetestream/blob/89cddea7e659fdbc95d82a9a8eb46716e7e03943/lib.php#L72

should be:

```
if ((string)$PAGE->pagetype == 'mod-assign-editsubmission' || (string)$PAGE->pagetype == 'mod-assign-gradingpanel') {
```

**Comment by PlaneteStream** [comment]
Hi mcardle, 

Apologies, this fix was added to the version on the repo but not here. I'll update this and TinyMCE now.
